<?php

namespace App\Utils\Constants\Statuses;

class TRANSAC_STATUS
{
    const PENDING_ENDORSER_APPROVAL = 'PENDING_ENDORSER_APPROVAL';
    const PENDING_BORROWING_APPROVAL = 'PENDING_BORROWING_APPROVAL';
    const APPROVED = 'APPROVED';
    const OVERDUE = 'OVERDUE_TRANSACTION_COMPLETION';
    const CANCELLED = 'CANCELLED';
    const DISAPPROVED = 'DISAPPROVED';
    const UNRELEASED = 'UNRELEASED';
    const ON_GOING = 'ON_GOING';
    const UNRETURNED = 'UNRETURNED';
    const TRANSACTION_COMPLETE = 'TRANSACTION_COMPLETE';

}